### ISSUE TITLE
No Grijjy.CloudLogging

### ISSUE THREAD

**Issue by limelect** [grijjy/GrijjyCloudLogger#1]
No Grijjy.CloudLogging
cannot find it

**Comment by allendrennan** [comment]
You need to download 3 repositories and include the GrijjyFoundation in your library path, which is where this unit Grijjy.CloudLogging is located.  See the installation instructions here,
https://github.com/grijjy/GrijjyCloudLogger#installing-the-grijjycloudlogger
On 8/22/2017 2:04:05 PM, limelect <notifications@github.com> wrote:
No Grijjy.CloudLogging
cannot find it

**Comment by limelect** [comment]
Still NO SUCH FILE !!!!    CloudLogging
plz check where is it?

**Comment by allendrennan** [comment]
It has always been present here,
https://github.com/grijjy/GrijjyFoundation/blob/master/Grijjy.CloudLogging.pas
Did you actually pull the repository as it says in the instructions?

If you have a newer Delphi it's also available now in the GetIt Package Manager.
On 8/24/2017 6:22:17 AM, limelect <notifications@github.com> wrote:
Still NO SUCH FILE !!!! CloudLogging
plz check where is it?

**Comment by limelect** [comment]
For some reason the file was missing. may be old version.?
I downloaded again and it is OK.
Thanks
